# Generated by Django 5.1.3 on 2024-11-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
