# Use the official Nginx image as the base image
FROM nginx:1.25

# Remove the default Nginx configuration file (optional)
RUN rm /etc/nginx/conf.d/default.conf

# Copy your custom Nginx configuration into the container
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf

# Expose necessary ports (optional, as they are defined in docker-compose)
EXPOSE 80 443
