# Generated by Django 5.1.3 on 2024-12-31 11:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_emailverificationevent_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationevent',
            name='token',
            field=models.UUIDField(default=uuid.uuid1, editable=False),
        ),
    ]
